# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1436a87bd265547df6c6f8de44fae633be0faa64b1a6e482385787b1505ebcfcede48f3e4b0ee1f15f5100c393d0937886e4bd5c38481ecea2bd407fa30c51d

test:
  secret_key_base: 97f38a7b6325ae6d46eb0d55f6f02bc3eb0348ce8b76a861319c92429b0527732300b7a0da3f7e9a05a52714eff840f8285f83cd66fe3fadc38ba8c774578698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
